Added Discord like welcome messages
osdc/bots pull request #22
Opened 2020-02-21 20:13 UTC by DelusionalOptimist

#21

2020-02-22 16:03 UTC, sidntrivedi012 commented
> #21

@DelusionalOptimist When any of your Pull request solves any issue, add a description like Fixes #21 . Then, Github can track it down.

2020-02-22 16:09 UTC, sidntrivedi requested changes

2020-02-22 16:09 UTC, sidntrivedi012 commented on telegram-bot/main.go
> +		fmt.Sprintf("Welcome %s, Welcome to OSDC, enjoy your stay :) Leave: Hopefully you come back to OSDC", User),
Umm..does it make sense to write welcome and leave message together?

2020-02-22 16:09 UTC, sidntrivedi012 commented on telegram-bot/main.go
> +	bot.Send(reply2)
Instead of sending `reply1` and then `reply2`, can we just concatenate them together and send as a one message?

2020-02-22 16:09 UTC, sidntrivedi012 commented on telegram-bot/main.go
> +		fmt.Sprintf("%s joined your party.", User),
Replace`your` with `our`.

2020-02-22 16:09 UTC, sidntrivedi012 commented on telegram-bot/main.go
> +		fmt.Sprintf("Brace yourselves. %s just joined the chat.", User),
Why are we using `fmt.Sprintf` here? Can't we just store the messages in an array and then after replacing the name of the user where needed, we can directly send it?

2020-02-23 16:19 UTC, DelusionalOptimist commented
@sidntrivedi012 I have made the discussed changes. Please review.

2020-02-23 16:50 UTC, sidntrivedi approved these changes
The changes LGTM. Nice work @DelusionalOptimist 💯🎉

2020-02-23 16:51 UTC, sidntrivedi012 commented
Since, We have not yet fully added Discord based messages so, changing the issue title.

2020-02-23 16:54 UTC, merged

2020-02-23 16:55 UTC, sidntrivedi012 commented
@DelusionalOptimist Nit: Never again push changes from master branch. Make a different branch and push changes from that branch.

Also, are you interested in working on more issues of the bot?😃