Changed the timezone used for saving meetups and scheduling reminders
osdc/bots pull request #44
Opened 2020-10-17 09:34 UTC by starkah

Fixes #41

2020-10-17 11:42 UTC, daemon1024 requested changes
@starkah Thanks for the PR 😄 . Requested some changes. Rest LGTM

@sidntrivedi012 @DelusionalOptimist What do you think?

2020-10-17 11:42 UTC, daemon1024 commented on telegram-bot/meetup.go
> +	Venue  venue `json:"venue"`
I dont think this change was intentional, kindly revert it back.

2020-10-17 11:42 UTC, daemon1024 commented on telegram-bot/meetup.go
> +	Group  group `json:"group"`
same here

2020-10-17 11:42 UTC, daemon1024 commented on telegram-bot/meetup.go
> +			panic(err)
I don't think panic is preferred. Instead `log.Print(err)` and send a bot message. We are planning to do it in #43 but as well as start here only :).

cc @sidntrivedi012

2020-10-17 13:52 UTC, DelusionalOptimist reviewed
I changed the timezone of my system  to UTC to test the changes. The reminder works fine. Great job :+1: .

Just one thing, when sending a reminder the bot still uses its local timezone. So you'll need to modify `reminder` and `nextmeetup` functions too.    
![starkah_bot_test](https://user-images.githubusercontent.com/54525605/96338540-6e8bb100-10ac-11eb-88e1-e7c94233ba17.jpg)

2020-10-18 04:48 UTC, starkah commented
@daemon1024 @DelusionalOptimist thanks for pointing out the necessary changes. I'm on it.

2020-10-18 15:01 UTC, starkah commented
@DelusionalOptimist Wouldn't it be more easier for the user if the reminder was in it's local time zone?
I suggest that in the first line of the reminder we could change it from "MEETUP REMINDER!" to " REMINDER - MEETUP IN 2 HOURS" or something similar. What do you think?

2020-10-18 15:11 UTC, daemon1024 commented
@starkah Note that the users are the members of OSDC and IST would be the local timezone for em :) But the bot can be deployed anywhere and the timezone of the developer's local system or any environment shouldn't be a dependency.

2020-10-18 15:22 UTC, starkah commented
@daemon1024 Makes sense. I'll try to do that.

2020-10-26 12:14 UTC, daemon1024 requested changes
Some small nits rest LGTM.

2020-10-26 12:14 UTC, daemon1024 commented on telegram-bot/meetup.go
> +		//stops the scheduler when meetup is done
```suggestion
		//stops the scheduler when reminder is sent
```

2020-10-26 12:14 UTC, daemon1024 commented on telegram-bot/meetup.go
> +		bot.Send(tbot.NewMessage(ID, "Couldn't detect the timezone, please try again"))
```suggestion
		bot.Send(tbot.NewMessage(ID, "Couldn't detect the timezone while processing reminder, please try again"))
```

2020-10-26 12:14 UTC, daemon1024 commented on telegram-bot/meetup.go
> +		bot.Send(tbot.NewMessage(ID, "Couldn't detect the timezone, please try again"))
```suggestion
		bot.Send(tbot.NewMessage(ID, "Couldn't detect the timezone while saving meetup, please try again"))
```

2020-10-27 06:00 UTC, daemon1024 approved these changes

2020-10-27 10:31 UTC, DelusionalOptimist approved these changes
LGTM. Great work @starkah. :rocket:

2020-10-27 10:40 UTC, merged