Fixes, Removed else if statements and added dynamic command handling
osdc/bots pull request #63
Opened 2020-11-11 16:21 UTC by reapedjuggler

Fixes #61, Implemented the code using dynamic command handling instead of else if statements, All the commands are now .js files under the command directory with their respective name.

2020-11-11 16:33 UTC, reapedjuggler commented
Here is a screenshot of the working.
![Screenshot_20201111-215458__01__01](https://user-images.githubusercontent.com/52465652/98838019-b0203980-2469-11eb-8d44-177bddddd47f.jpg)

2020-11-16 12:42 UTC, daemon1024 requested changes
Small nit, Rest LGTM :smile: Also can you please resolve the merge conflicts? Thanks. Sorry for the delayed review :)

2020-11-16 12:42 UTC, daemon1024 commented on discord-bot/commands/irc.js
> +    description: 'irc Link',
```suggestion
    description: 'IRC Link',
```

2020-11-16 13:38 UTC, reapedjuggler commented
No worries, done with the changes :)

2020-11-16 13:39 UTC, daemon1024 approved these changes

2020-11-16 13:40 UTC, merged